### ISSUE TITLE
How to fix header of the sheet?

### ISSUE THREAD

**Issue by happimaker** [manufont/react-swipeable-bottom-sheet#13]
I want to fix header so that I can control the header swipeable after I opened the sheet and scrolled down.

**Comment by nghiepit** [comment]
@happimaker 
You can do it with custom `css`
```css
.ReactSwipeableBottomSheet--open > div:first-child {
  position: sticky;
  top: 0;
}
```
